#!/bin/bash
set -uo pipefail

A=/opt/odoo/deploy/sgc-rent-mt/addons/sgc_offplan_rental_property_management
ROOT=/opt/odoo/deploy/sgc-rent-mt
Q="$ROOT/_quarantine_$(date +%Y%m%d)"
mkdir -p "$Q/scripts"

echo "=== quarantine dir: $Q ==="
echo ""

echo "--- 1. dead code files (unreachable, would collide if ever imported) ---"
for f in sale_contract_installment.py verify_luxury.py; do
  if [ -f "$A/$f" ]; then
    cp -p "$A/$f" "$Q/$f"
    rm -f "$A/$f"
    echo "  quarantined + removed: $f"
  else
    echo "  not present (already clean): $f"
  fi
done

echo ""
echo "--- 2. temp/audit scripts from deploy root (outside the addon) ---"
moved=0
for f in "$ROOT"/*.py; do
  [ -f "$f" ] || continue
  b=$(basename "$f")
  mv "$f" "$Q/scripts/$b"
  moved=$((moved+1))
done
echo "  archived $moved helper scripts to $Q/scripts/"

echo ""
echo "--- 3. __pycache__ in the addon ---"
c=$(find "$A" -name '__pycache__' -type d | wc -l)
find "$A" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null
echo "  removed $c __pycache__ dirs (regenerated by Odoo on demand)"

echo ""
echo "--- 4. verify addon root is now clean ---"
find "$A" -maxdepth 1 -type f -name '*.py' | while read f; do
  b=$(basename "$f")
  case "$b" in
    __init__.py|__manifest__.py) echo "  expected: $b" ;;
    *) echo "  *** STILL PRESENT: $b ***" ;;
  esac
done
echo ""
echo "  addon root non-python clutter:"
ls "$A" | grep -v -e '^models$' -e '^views$' -e '^static$' -e '^controllers$' -e '^wizard$' -e '^report$' \
  -e '^security$' -e '^data$' -e '^migrations$' -e '^tests$' -e '^compat$' -e '^i18n$' \
  -e '^__init__.py$' -e '^__manifest__.py$' -e '^README' -e '^LICENSE' -e '^\.' -e '^background' -e '^banner' || echo "  (none)"

echo ""
echo "--- 5. py_compile sanity after cleanup ---"
python3 -m py_compile "$A/models/core/property_details.py" && echo "  property_details.py OK"
python3 -c "import ast,sys; ast.parse(open('$A/__init__.py').read()); print('  __init__.py OK')"

echo ""
echo "CLEANUP_DONE"