"""Diagnose where refunds / credit notes actually live in this database.

The initial bucket counts showed 0 posted ``out_refund`` and 0 posted
``in_refund``, yet the user needs refunds identified.  This probes every
plausible place they could be hiding:

* move_type x state (including draft and cancelled)
* invoices carrying a negative amount
* invoices in a "reversed" payment state
* ``account.payment`` by payment_type x partner_type x state
* reversal entries generated by Odoo's own reverse action
* manual journal entries that carry a refund-like reference
"""

from __future__ import annotations

import sys

from pgre_client import OdooClient, OdooError


def section(title: str) -> None:
    print()
    print("=" * 78)
    print(title)
    print("=" * 78)


def main() -> int:
    client = OdooClient()
    print(f"Connected: {client.url} db={client.db} uid={client.uid} "
          f"transport={client.transport_name}")

    section("1. account.move  -  move_type x state (ALL records, nothing filtered)")
    groups = client.execute_kw("account.move", "read_group", [], {
        "domain": [],
        "fields": ["move_type", "state"],
        "groupby": ["move_type", "state"],
        "lazy": True,
    }) or []
    totals: dict[str, int] = {}
    for g in groups:
        mt = str(g.get("move_type"))
        st = str(g.get("state"))
        n = int(g.get("move_type_count", 0))
        totals[(mt, st)] = n
    move_types = sorted({k[0] for k in totals})
    states = sorted({k[1] for k in totals})
    header = f"{'move_type':<18}" + "".join(f"{s:>10}" for s in states) + f"{'TOTAL':>10}"
    print(header)
    print("-" * len(header))
    for mt in move_types:
        row = f"{mt:<18}"
        tot = 0
        for st in states:
            n = totals.get((mt, st), 0)
            tot += n
            row += f"{n:>10,}" if n else f"{'.':>10}"
        row += f"{tot:>10,}"
        print(row)
    grand = sum(totals.values())
    print("-" * len(header))
    print(f"{'ALL':<18}{'':>10}{'':>10}{'':>10}{grand:>10,}")

    section("2. Refund-shaped records, searched everywhere")
    probes = [
        ("posted out_refund (customer credit note)",
         [("move_type", "=", "out_refund"), ("state", "=", "posted")]),
        ("ANY out_refund (incl. draft/cancel)",
         [("move_type", "=", "out_refund")]),
        ("posted in_refund (vendor credit note)",
         [("move_type", "=", "in_refund"), ("state", "=", "posted")]),
        ("ANY in_refund",
         [("move_type", "=", "in_refund")]),
        ("invoices with NEGATIVE amount_total",
         [("move_type", "in", ["out_invoice", "in_invoice"]),
          ("amount_total", "<", 0)]),
        ("any record with negative amount_total",
         [("amount_total", "<", 0), ("move_type", "!=", "entry")]),
        ("invoices with payment_state=reversed",
         [("payment_state", "=", "reversed")]),
        ("invoices with payment_state=reversed_in_payment",
         [("payment_state", "=", "reversed_in_payment")]),
    ]
    for label, domain in probes:
        try:
            n = client.search_count("account.move", domain)
        except OdooError as exc:
            n = f"ERR {exc}"[:40]
        flag = "  <-- FOUND" if isinstance(n, int) and n else ""
        print(f"  {label:<48} {n}{flag}")

    section("3. Reversal trail: journal entries Odoo generated from reversals")
    # When Odoo reverses a posted invoice it creates a copy with the opposite
    # move_type plus a reversal link. Those copies are real money back.
    for mt in ("out_invoice", "in_invoice", "out_refund", "in_refund"):
        rows = client.search_read(
            "account.move",
            [("move_type", "=", mt), ("state", "=", "posted"), ("amount_total", "<", 0)],
            ["name", "amount_total", "payment_state", "reversal_move_ids", "invoice_origin"],
            limit=8, order="invoice_date desc")
        if rows:
            print(f"  {mt} with negative total: {len(rows)} shown")
            for r in rows:
                print(f"    {r.get('name')!s:<22} {r.get('amount_total')!s:>14} "
                      f"state={r.get('payment_state')} origin={r.get('invoice_origin')!s:.30}")

    section("4. account.payment  -  payment_type x partner_type x state")
    groups = client.execute_kw("account.payment", "read_group", [], {
        "domain": [],
        "fields": ["payment_type", "partner_type", "state"],
        "groupby": ["payment_type", "partner_type", "state"],
        "lazy": True,
    }) or []
    p_rows: dict[tuple[str, str], dict[str, int]] = {}
    for g in groups:
        k = (str(g.get("payment_type")), str(g.get("partner_type")))
        p_rows.setdefault(k, {})[str(g.get("state"))] = int(g.get("payment_type_count", 0))
    states = sorted({s for r in p_rows.values() for s in r})
    header = f"{'payment_type':<12}{'partner_type':<14}" + "".join(f"{s:>10}" for s in states)
    print(header)
    print("-" * len(header))
    for (pt, ptype), r in sorted(p_rows.items()):
        print(f"{pt:<12}{ptype:<14}" + "".join(f"{r.get(s, 0):>10,}" for s in states))

    section("5. MONEY OUT to customers (refunds paid) - posted only")
    rows = client.search_read(
        "account.payment",
        [("payment_type", "=", "outbound"), ("partner_type", "=", "customer"),
         ("state", "not in", ["draft", "cancel"])],
        ["name", "date", "amount", "partner_id", "payment_reference", "is_reconciled"],
        limit=15, order="date desc")
    print(f"  count: {client.search_count('account.payment', [('payment_type','=','outbound'),('partner_type','=','customer'),('state','not in',['draft','cancel'])])}")
    for r in rows:
        print(f"  {r.get('name')!s:<18} {str(r.get('date')):<12} {r.get('amount')!s:>12} "
              f"{(r.get('partner_id') or ['',''])[1]!s:.34} ref={r.get('payment_reference')!s}")

    section("6. Journals in use")
    journals = client.read("account.journal", client.search_ids("account.journal", [], limit=300),
                           ["code", "name", "type"])
    by_type: dict[str, int] = {}
    for j in journals:
        by_type[str(j.get("type"))] = by_type.get(str(j.get("type")), 0) + 1
    for t, n in sorted(by_type.items()):
        print(f"  {t:<14} {n:>4} journals")

    section("VERDICT")
    for mt in ("out_refund", "in_refund"):
        total = sum(v for (m, _), v in totals.items() if m == mt)
        print(f"  {mt}: {total} record(s) in the whole database")
    neg = client.search_count("account.move",
                              [("amount_total", "<", 0), ("move_type", "!=", "entry")])
    print(f"  non-entry records with a negative total: {neg}")
    print()
    print("  If refunds were recorded as manual journal entries (move_type='entry')")
    print("  they will NOT appear in the refund buckets - they will surface in the")
    print("  journal_entries / journal_entry_lines datasets instead.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OdooError, Exception) as exc:  # noqa: BLE001
        print(f"\nFAILED: {exc}", file=sys.stderr)
        raise SystemExit(1)