# -*- coding: utf-8 -*-
from odoo import _, api, fields, models


class PropertySubProject(models.Model):
    _name = 'property.sub.project'
    _inherit = ['mail.thread', 'mail.activity.mixin', 'sgc.critical.audit.mixin']
    _description = 'Property Sub Project'
    _order = 'name'

    name = fields.Char(string='Sub Project Name', required=True)
    code = fields.Char(string='Sub Project Code')
    project_id = fields.Many2one('property.project', string='Project', required=True)
    description = fields.Html(string='Description')
    active = fields.Boolean(string='Active', default=True)
    company_id = fields.Many2one('res.company', string='Company', default=lambda self: self.env.company)
    region_id = fields.Many2one('property.region', string='Region')

    image_1920 = fields.Binary(string='Image', attachment=True)
    image_512 = fields.Binary(string='Image (512px)', compute='_compute_images', store=True, attachment=True)
    image_256 = fields.Binary(string='Image (256px)', compute='_compute_images', store=True, attachment=True)
    property_count = fields.Integer(string='Properties', compute='_compute_property_count')

    # Commercial orientation + installment plan (mirrors property.project;
    # applied to units bulk-created from this sub-project).
    sale_lease = fields.Selection([
        ('sale', 'Sale'),
        ('lease', 'Lease'),
        ('both', 'Both'),
    ], string='Sale/Lease')
    payment_schedule_id = fields.Many2one(
        'payment.schedule',
        string='Installment Plan',
        help='Payment plan template applied to units created from this sub-project.',
    )

    # Bulk unit creation layout. floor_created tracks how many floors have
    # already been generated so the wizard continues numbering from the next
    # floor instead of restarting at 1.
    total_floors = fields.Integer(string='Total Floors', default=0)
    units_per_floor = fields.Integer(string='Units per Floor', default=0)
    floor_created = fields.Integer(
        string='Floors Created',
        default=0,
        help='Floors already generated by the bulk unit wizard.',
    )

    # Location (defaults from the parent project; copied to units created here).
    address = fields.Text(string='Address')
    city = fields.Char(string='City')
    state_id = fields.Many2one('res.country.state', string='State')
    country_id = fields.Many2one('res.country', string='Country')
    zip = fields.Char(string='ZIP')

    @api.depends('image_1920')
    def _compute_images(self):
        for rec in self:
            rec.image_512 = rec.image_1920
            rec.image_256 = rec.image_1920

    @api.depends()
    def _compute_property_count(self):
        for rec in self:
            rec.property_count = self.env['property.details'].search_count(
                [('sub_project_id', '=', rec.id)]
            )

    def action_view_properties(self):
        return {
            "name": "Properties",
            "type": "ir.actions.act_window",
            "domain": [("sub_project_id", "=", self.id)],
            "view_mode": "kanban,list,form",
            "context": {"create": False, "default_sub_project_id": self.id},
            "res_model": "property.details",
            "target": "current",
        }

    def action_open_unit_wizard(self):
        """Open the bulk unit-creation wizard for units under this sub-project."""
        self.ensure_one()
        return {
            'name': _('Bulk Create Units'),
            'type': 'ir.actions.act_window',
            'res_model': 'unit.creation',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'active_id': self.id,
                'unit_from': 'sub_project',
            },
        }
